/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */
import type { Funcionario } from './funcionario';
import type { Gestao } from './gestao';

export interface Auth {
  id: number;
  code: string;
  password: string;
  accessToken?: string;
  tokenExpiresAt?: string;
  role: string;
  funcionario?: Funcionario;
  gestao?: Gestao;
  createdAt: string;
  updatedAt: string;
}
