/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */

/**
 * Papel do usuário
 */
export type CreateAuthDtoRole = typeof CreateAuthDtoRole[keyof typeof CreateAuthDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAuthDtoRole = {
  funcionario: 'funcionario',
  gestor: 'gestor',
} as const;
