/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */

export interface CreateHistoricoProducaoDto {
  /** ID do pedido associado */
  pedidoId: number;
  /** ID do funcionário responsável */
  funcionarioId: number;
  /** Ação realizada */
  acao: string;
  /** Detalhes adicionais sobre a ação */
  detalhes?: string;
  /** ID do motivo de interrupção */
  motivoInterrupcaoId?: number;
  /** Data e hora em que a ação foi registrada */
  dataHora?: string;
}
