/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */
import type { Auth } from './auth';

export interface Gestao {
  id: number;
  code: string;
  name: string;
  department: string;
  role: string;
  auth?: Auth;
  createdAt: string;
  updatedAt: string;
}
