/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */
import type { Order } from './order';
import type { Funcionario } from './funcionario';

export interface OrderTracking {
  /** ID único do rastreamento */
  id: number;
  /** Pedido associado */
  order: Order;
  /** Funcionário responsável */
  funcionarios: Funcionario;
  /** Hora de início do rastreamento */
  startTime: string;
  /** Hora de término do rastreamento */
  endTime?: string;
  /** Quantidade de peças perdidas */
  lostQuantity?: number;
  /** Quantidade de peças processadas */
  processedQuantity?: number;
}
