/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */

export type OrdersControllerCreateEtapaBody = {
  nome?: string;
  funcionarioCode?: string;
};
