/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */
import type { Product } from './product';
import type { Funcionario } from './funcionario';
import type { OrderTracking } from './orderTracking';
import type { Etapa } from './etapa';

export interface Order {
  /** ID único do pedido */
  id: number;
  /** Número da Ordem de Pedido (OP) */
  orderNumber: string;
  /** Nome do pedido */
  name: string;
  /** Produto associado */
  product: Product;
  /** Funcionário responsável */
  funcionarioResposavel: Funcionario;
  /** Quantidade de peças no lote */
  lotQuantity: number;
  /** Destino final do lote */
  finalDestination: string;
  /** Rastreamentos do pedido */
  trackings: OrderTracking[];
  /** Status do pedido */
  status: string;
  /** Etapas do pedido */
  etapas: Etapa[];
  /** Data de criação do pedido */
  created_at: string;
  /** Data de atualização do pedido */
  updated_at: string;
}
