/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */

export interface Product {
  /** ID único do produto */
  id: number;
  /** Código do produto */
  code: string;
  /** Nome do produto */
  name: string;
  /** Descrição do produto */
  description?: string;
  /** Preço do produto */
  price: number;
  /** Quantidade em estoque */
  quantity: number;
}
