/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */

export interface TrackOrderDto {
  /** ID da ordem de serviço */
  orderId: number;
  /** Código do funcionário */
  employeeCode: string;
  /** Quantidade de peças perdidas */
  lostQuantity?: number;
  /** Quantidade de peças processadas */
  processedQuantity?: number;
}
