/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */

export interface UpdateFuncionarioDto {
  /** Código do funcionário */
  code?: string;
  /** Nome do funcionário */
  nome?: string;
  /** Cargo do funcionário */
  cargo?: string;
  /** Salário do funcionário */
  salario?: number;
}
