/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NestJS API
 * API documentation for NestJS with Swagger, Orval, and MikroORM
 * OpenAPI spec version: 1.0
 */

export interface UpdateGestorDto {
  /** Código do gestor */
  code?: string;
  /** Nome do gestor */
  name?: string;
  /** Departamento do gestor */
  department?: string;
  /** Cargo do gestor */
  role?: string;
}
